# Inspiritag - Micro-framework for Flutter.
#
# Website: https://inspiritag.dev
# Official repository: https://github.com/inspiritag-core/inspiritag
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Inspiritag Flutter application.

publish_to: 'none'

version: 1.0.4+15

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  url_launcher: ^6.3.2
  google_fonts: ^6.3.1
  analyzer: ^8.1.1
  intl: ^0.20.2
  nylo_framework: ^6.8.16
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  flutter_local_notifications: ^19.4.2
  font_awesome_flutter: ^10.10.0
  scaffold_ui: ^1.2.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.3
  visibility_detector: ^0.4.0+2
  video_thumbnail: ^0.5.3
  video_player: ^2.10.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  firebase_messaging: ^16.0.2
  sign_in_with_apple: ^7.0.1
  cached_network_image: ^3.4.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.4.0
  image_picker: ^1.0.7
  http: ^1.2.1
  path: ^1.8.3
  firebase_auth: ^6.1.0
  dio: ^5.9.0
  share_plus: ^12.0.1
  in_app_purchase: ^3.1.11
dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/images/logo.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/images/logo.png"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - lang/
    - .env
